# Generated by Django 5.0.6 on 2024-06-05 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inform',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informs', related_query_name='informs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informread',
            name='inform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', related_query_name='reads', to='inform.inform'),
        ),
        migrations.AlterField(
            model_name='informread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', related_query_name='reads', to=settings.AUTH_USER_MODEL),
        ),
    ]
