# Generated by Django 5.0.6 on 2024-06-02 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oadepartment',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_departments', related_query_name='manager_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oauser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Actived'), (2, 'Unactive'), (3, 'Locked')], default=2),
        ),
    ]
